#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building execline (one of the requirements to building s6)
# Adjust these as neccessary

EXECLINE_VERSION="execline-1.3.1.1"

# You shouldn't need to change these, but you can as required

EXECLINE_FILE="$EXECLINE_VERSION.tar.gz"
EXECLINE_URL="http://skarnet.org/software/execline/$EXECLINE_FILE"

# download execline into packages
curl -o /package/$EXECLINE_FILE $EXECLINE_URL

# unzip the execline package
cd /package
tar -zxpvf $EXECLINE_FILE
rm $EXECLINE_FILE

# setup the configuration
cd admin/$EXECLINE_VERSION

echo musl-gcc > conf-compile/conf-cc
echo musl-gcc -static > conf-compile/conf-ld
echo musl-gcc > conf-compile/conf-dynld
echo /usr/bin > conf-compile/conf-install-command
touch conf-compile/flag-allstatic
package/compile
rm -f package/library.so.exported

# install execline
make
sudo make install
make clean
