#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building musil
# Musl will be used to compile s6 into static executables
# Adjust these as neccessary

MUSIL_VERSION="musl-1.0.4"

# You shouldn't need to change these, but you can as required

MUSIL_FILE="$MUSIL_VERSION.tar.gz"
MUSIL_URL="http://www.musl-libc.org/releases/$MUSIL_FILE"

# download musil into packages
curl -o /build/$MUSIL_FILE $MUSIL_URL

# unzip the musil package
cd /build
tar -xf $MUSIL_FILE

# setup the configuration, and install
cd /build/$MUSIL_VERSION
CFLAGS="-fno-toplevel-reorder -fno-stack-protector" ./configure --prefix=/usr/musl --exec-prefix=/usr --disable-shared
make
sudo make install
make clean

# clean up
rm /build/$MUSIL_FILE
rm -rf /build/$MUSIL_VERSION
