#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building s6
# Adjust these as neccessary

s6_VERSION="s6-1.1.3.2"

# You shouldn't need to change these, but you can as required

s6_FILE="$s6_VERSION.tar.gz"
s6_URL="http://www.skarnet.org/software/s6/$s6_FILE"

# download s6 into packages
curl -o /package/$s6_FILE $s6_URL

# unzip the s6 package
cd /package
tar -zxpvf $s6_FILE
rm $s6_FILE

# setup the configuration
cd admin/$s6_VERSION

echo musl-gcc > conf-compile/conf-cc
echo musl-gcc -static > conf-compile/conf-ld
echo musl-gcc > conf-compile/conf-dynld
echo /usr/bin > conf-compile/conf-install-command
touch conf-compile/flag-allstatic
package/compile
rm -f package/library.so.exported

# make s6
make
sudo make install
make clean

# gzip the files ready to go
tar -zcf /vagrant/dist/$s6_VERSION-static.tar.gz -C /package/admin/s6/command .
