#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building execline (one of the requirements to building s6)
# Adjust these as neccessary

SKALIBS_VERSION="skalibs-1.6.0.0"

# You shouldn't need to change these, but you can as required

SKALIBS_FILE="$SKALIBS_VERSION.tar.gz"
SKALIBS_URL="http://skarnet.org/software/skalibs/$SKALIBS_FILE"

# download execline into packages
curl -o /package/$SKALIBS_FILE $SKALIBS_URL

# unzip the execline package
cd /package
tar -zxpvf $SKALIBS_FILE
rm $SKALIBS_FILE

# setup the configuration, use musil-gcc to build skalibs
cd prog/$SKALIBS_VERSION

echo musl-gcc > conf-compile/conf-cc
echo musl-gcc -static > conf-compile/conf-ld
echo musl-gcc > conf-compile/conf-dynld
echo /usr/bin > conf-compile/conf-install-command
touch conf-compile/flag-allstatic
package/compile
rm -f package/library.so.exported

# install skalib
make
sudo make install
make clean
